In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.arange(0, 10, 2)
c = np.linspace(0, 1, 5)
z = np.zeros((2, 3),dtype=np.float32)
o = np.ones_like(z)
r = np.random.default_rng(42).normal(size=(3, 4))
for name, arr in dict(a=a, b=b, c=c, o=o,r=r).items():
    print(name, arr.shape, arr.dtype, "\n", arr,"\n")

a (3,) int64 
 [1 2 3] 

b (5,) int64 
 [0 2 4 6 8] 

c (5,) float64 
 [0.   0.25 0.5  0.75 1.  ] 

o (2, 3) float32 
 [[1. 1. 1.]
 [1. 1. 1.]] 

r (3, 4) float64 
 [[ 0.30471708 -1.03998411  0.7504512   0.94056472]
 [-1.95103519 -1.30217951  0.1278404  -0.31624259]
 [-0.01680116 -0.85304393  0.87939797  0.77779194]] 



In [4]:
x = np.arange(10)
s = x[2:7]
s[0] = 999
print("x after editing s:", x)

x after editing s: [  0   1 999   3   4   5   6   7   8   9]


In [5]:
M = np.arange(12).reshape(3,4)
print(M, "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



In [6]:
print("row 1:",M[1])

row 1: [4 5 6 7]


In [8]:
print("col 2 :", M[:,2])

col 2 : [ 2  6 10]


In [9]:
print("submatrix:", M[0:2, 1:3])

submatrix: [[1 2]
 [5 6]]


In [10]:
print(M[:2])

[[0 1 2 3]
 [4 5 6 7]]


In [13]:
print("fancy index:",M[[0,2],[1,3]])
print("boolean mask:\n",M[M%2 == 0])

fancy index: [ 1 11]
boolean mask:
 [ 0  2  4  6  8 10]


In [14]:
import pandas as pd

In [15]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

# 生成医学数据示例
np.random.seed(42)
patients = pd.DataFrame({
    'age': np.random.normal(45, 15, 1000),
    'systolic_bp': np.random.normal(120, 20, 1000),
    'diastolic_bp': np.random.normal(80, 10, 1000),
    'cholesterol': np.random.normal(200, 40, 1000)
})

# 描述性统计
print("描述性统计:")
print(patients.describe())

# 正态性检验
statistic, p_value = stats.normaltest(patients['systolic_bp'])
print(f"血压正态性检验: p = {p_value:.4f}")

# 相关性分析
correlation = patients.corr()
print("相关系数矩阵:")
print(correlation)

描述性统计:
               age  systolic_bp  diastolic_bp  cholesterol
count  1000.000000  1000.000000   1000.000000  1000.000000
mean     45.289981   121.416725     80.058342   199.251231
std      14.688239    19.949088      9.834543    41.085301
min      -3.619010    61.192227     49.804878    82.822052
25%      35.286145   107.875166     73.520004   170.503182
50%      45.379509   121.261543     79.997492   200.007383
75%      54.719158   134.577644     86.609153   226.677816
max     102.790972   183.862151    119.262377   329.723719
血压正态性检验: p = 0.7373
相关系数矩阵:
                   age  systolic_bp  diastolic_bp  cholesterol
age           1.000000    -0.040400      0.022129    -0.013321
systolic_bp  -0.040400     1.000000     -0.011199    -0.054698
diastolic_bp  0.022129    -0.011199      1.000000     0.021586
cholesterol  -0.013321    -0.054698      0.021586     1.000000


In [16]:
a, b = 1, 2 

In [17]:
a

1

In [18]:
b

2

In [19]:
In [32]: seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [33]: for a, b, c in seq:
   ....:     print(f'a={a}, b={b}, c={c}')

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [20]:
import pandas as pd
import numpy as np
import matplotlib.pylot as plt

ModuleNotFoundError: No module named 'matplotlib.pylot'

In [21]:
import matplotlib.pyplot as plt

In [22]:
#set chinese
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axex.unicode_minus'] = False

KeyError: 'axex.unicode_minus is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'

In [23]:
plt.rcParams['font.sans-serif'] = ['SimHei']  # 用黑体显示中文
plt.rcParams['axes.unicode_minus'] = False  # 正常显示负号

In [24]:
data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七', '孙八', '周九', '吴十'],
    '语文': [85, 92, 78, 88, 95, 72, 90, 83],
    '数学': [90, 88, 65, 92, 87, 70, 85, 91],
    '英语': [88, 95, 80, 85, 90, 68, 92, 86],
    '物理': [82, 90, 72, 88, 93, 65, 87, 89],
    '化学': [86, 87, 75, 90, 91, 70, 88, 85]
}

In [26]:
df = pd.DataFrame(data)

In [27]:
print("=" * 50)
print(f"raw data:{df} ")



raw data:   姓名  语文  数学  英语  物理  化学
0  张三  85  90  88  82  86
1  李四  92  88  95  90  87
2  王五  78  65  80  72  75
3  赵六  88  92  85  88  90
4  钱七  95  87  90  93  91
5  孙八  72  70  68  65  70
6  周九  90  85  92  87  88
7  吴十  83  91  86  89  85 
